// Embedded-asset fs patch, paired with deploy/embedded-assets.mjs (generated by
// scripts/vercel-bundles.mjs). Vercel function outputs only contain traced files and
// functions.includeFiles is ignored for this project, so the bundle carries the repo files the API
// reads at runtime and this patch serves them from memory for paths under the repo root.
// Must be installed before any framework module initialises (deploy/server.ts does).
import { EMBEDDED } from "./embedded-assets.mjs";

const decode = (b64) => Buffer.from(b64, "base64");

export function installEmbeddedFs(repoRoot) {
  const fs = require("node:fs");
  const prefix = repoRoot.replace(/\/+$/, "") + "/";
  const keyOf = (p) => {
    if (typeof p !== "string" && !(p instanceof URL)) return null;
    const norm = String(p).replace(/\\/g, "/");
    if (!norm.startsWith(prefix)) return null;
    return norm.slice(prefix.length);
  };

  const origReadFileSync = fs.readFileSync;
  fs.readFileSync = function (p, options) {
    const key = keyOf(p);
    if (key && key in EMBEDDED) {
      const buf = decode(EMBEDDED[key]);
      const enc = typeof options === "string" ? options : options?.encoding;
      return enc ? buf.toString(enc) : buf;
    }
    return origReadFileSync.apply(fs, arguments);
  };

  const origExistsSync = fs.existsSync;
  fs.existsSync = function (p) {
    const key = keyOf(p);
    if (key && key in EMBEDDED) return true;
    return origExistsSync.apply(fs, arguments);
  };

  const origStatSync = fs.statSync;
  fs.statSync = function (p, options) {
    const key = keyOf(p);
    if (key && key in EMBEDDED) {
      const size = decode(EMBEDDED[key]).length;
      const stat = {
        size,
        isFile: () => true,
        isDirectory: () => false,
        isSymbolicLink: () => false,
      };
      return options?.bigint ? stat : stat;
    }
    return origStatSync.apply(fs, arguments);
  };
}
