import { EMBEDDED } from "./embedded-assets.mjs";
// Bundled modules share one scope, so import.meta.dirname is the bundle file's directory (…/api);
// the repo root that mapped paths are keyed against is its parent.
const repoRoot = new URL("..", import.meta.url).pathname.replace(/\/+$/, "");
const keyOf = (p) => {
  if (typeof p !== "string" && !(p instanceof URL)) return null;
  const norm = String(p).split("\\").join("/");
  // harfbuzzjs reads its wasm via a hard-coded __dirname; map it wherever the bundle runs.
  const hb = "/node_modules/harfbuzzjs/";
  const hbAt = norm.indexOf(hb);
  if (hbAt >= 0) return "node_modules/harfbuzzjs/" + norm.slice(hbAt + hb.length);
  if (!norm.startsWith(repoRoot + "/")) return null;
  return norm.slice(repoRoot.length + 1);
};
const embeddedBuf = (key) => Buffer.from(EMBEDDED[key], "base64");
import { createRequire as __shimCreateRequire } from "node:module";
const real = __shimCreateRequire(import.meta.url)("node:fs");
export const readFileSync = function (p, options) {
  const key = keyOf(p);
  if (key && key in EMBEDDED) {
    const buf = embeddedBuf(key);
    const enc = typeof options === "string" ? options : options?.encoding;
    return enc ? buf.toString(enc) : buf;
  }
  return real.readFileSync(p, options);
};
export const existsSync = function (p) {
  const key = keyOf(p);
  if (key && key in EMBEDDED) return true;
  return real.existsSync(p);
};
export const statSync = function (p, options) {
  const key = keyOf(p);
  if (key && key in EMBEDDED) {
    const size = embeddedBuf(key).length;
    return { size, isFile: () => true, isDirectory: () => false, isSymbolicLink: () => false };
  }
  return real.statSync(p, options);
};
export const createReadStream = function (p, options) {
  const key = keyOf(p);
  if (!(key && key in EMBEDDED)) return real.createReadStream(p, options);
  const { Readable } = require("node:stream");
  return Readable.from(embeddedBuf(key));
};
export const appendFile = real.appendFile;
export const appendFileSync = real.appendFileSync;
export const access = real.access;
export const accessSync = real.accessSync;
export const chown = real.chown;
export const chownSync = real.chownSync;
export const chmod = real.chmod;
export const chmodSync = real.chmodSync;
export const close = real.close;
export const closeSync = real.closeSync;
export const copyFile = real.copyFile;
export const copyFileSync = real.copyFileSync;
export const cp = real.cp;
export const cpSync = real.cpSync;
export const createWriteStream = real.createWriteStream;
export const exists = real.exists;
export const fchown = real.fchown;
export const fchownSync = real.fchownSync;
export const fchmod = real.fchmod;
export const fchmodSync = real.fchmodSync;
export const fdatasync = real.fdatasync;
export const fdatasyncSync = real.fdatasyncSync;
export const fstat = real.fstat;
export const fstatSync = real.fstatSync;
export const fsync = real.fsync;
export const fsyncSync = real.fsyncSync;
export const ftruncate = real.ftruncate;
export const ftruncateSync = real.ftruncateSync;
export const futimes = real.futimes;
export const futimesSync = real.futimesSync;
export const glob = real.glob;
export const globSync = real.globSync;
export const lchown = real.lchown;
export const lchownSync = real.lchownSync;
export const lchmod = real.lchmod;
export const lchmodSync = real.lchmodSync;
export const link = real.link;
export const linkSync = real.linkSync;
export const lstat = real.lstat;
export const lstatSync = real.lstatSync;
export const lutimes = real.lutimes;
export const lutimesSync = real.lutimesSync;
export const mkdir = real.mkdir;
export const mkdirSync = real.mkdirSync;
export const mkdtemp = real.mkdtemp;
export const mkdtempSync = real.mkdtempSync;
export const mkdtempDisposableSync = real.mkdtempDisposableSync;
export const open = real.open;
export const openSync = real.openSync;
export const openAsBlob = real.openAsBlob;
export const readdir = real.readdir;
export const readdirSync = real.readdirSync;
export const read = real.read;
export const readSync = real.readSync;
export const readv = real.readv;
export const readvSync = real.readvSync;
export const readFile = real.readFile;
export const readlink = real.readlink;
export const readlinkSync = real.readlinkSync;
export const realpath = real.realpath;
export const realpathSync = real.realpathSync;
export const rename = real.rename;
export const renameSync = real.renameSync;
export const rm = real.rm;
export const rmSync = real.rmSync;
export const rmdir = real.rmdir;
export const rmdirSync = real.rmdirSync;
export const stat = real.stat;
export const statfs = real.statfs;
export const statfsSync = real.statfsSync;
export const symlink = real.symlink;
export const symlinkSync = real.symlinkSync;
export const truncate = real.truncate;
export const truncateSync = real.truncateSync;
export const unwatchFile = real.unwatchFile;
export const unlink = real.unlink;
export const unlinkSync = real.unlinkSync;
export const utimes = real.utimes;
export const utimesSync = real.utimesSync;
export const watch = real.watch;
export const watchFile = real.watchFile;
export const writeFile = real.writeFile;
export const writeFileSync = real.writeFileSync;
export const write = real.write;
export const writeSync = real.writeSync;
export const writev = real.writev;
export const writevSync = real.writevSync;
export const Dirent = real.Dirent;
export const Stats = real.Stats;
export const ReadStream = real.ReadStream;
export const WriteStream = real.WriteStream;
export const FileReadStream = real.FileReadStream;
export const FileWriteStream = real.FileWriteStream;
export const Utf8Stream = real.Utf8Stream;
export const _toUnixTimestamp = real._toUnixTimestamp;
export const Dir = real.Dir;
export const opendir = real.opendir;
export const opendirSync = real.opendirSync;
export const constants = real.constants;
export const promises = real.promises;
export default real;
